
reset;
option solver cplex;
model CSPP.mod;

# Lista delle istanze da testare
set ISTANZE_TXT = {"Istanze/Grid/Grid_100x100_7920/Grid_100x100_5940_27009.txt"};

for {istanza in ISTANZE_TXT} {
    printf "\n--- RISOLVO ISTANZA: %s ---\n", istanza;
    
    reset data;
    read {u in V, v in V} (d[u,v], c[u,v]) < istanza;
    
    solve;
    
    # Salvano i risultati (es. tempo di calcolo e costo ottimo) su un file di riepilogo
    printf "%s, %g, %g\n", istanza, Costo_Totale, _solve_time >> risultati_totali.csv;
}